### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by FND**
as discussed elsewhere

### CODE REVIEW

**Review by moonglum — COMMENTED** [review]
I like it. I added a bump of the Ruby dependencies as well. Why did you remove the package-lock.json?

**Comment by FND** [comment]
> Why did you remove the package-lock.json?

I didn't, but I did have a typo ("devDpendencies") that resulted in `package-lock.json` being reduced to complate-stream - thanks for spotting that! Fixed and squashed as 2c57a764db6fab78792381016a34769dc238279b.

**Comment by FND** [comment]
Also, I forgot to mention this: https://github.com/complate/complate-ruby/issues/1

**Comment by moonglum** [comment]
Great 🙇

**Pull request closed without merging**
